package com.tagtracker.app;

import android.app.Activity;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONObject;

/**
 * Pro / license screen. Free tier = 1 tag + 24h history. A Pro key (device-bound) unlocks
 * multiple tags, full history, export and alerts. Keys are generated by the seller and entered here;
 * verification is offline. This app is open-source (GPL) — the key is a convenience/honour gate.
 */
public class LicenseActivity extends Activity {
    static final String CONTACT_EMAIL = "meshkat4u@gmail.com";

    private String deviceId;
    private LinearLayout root;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setTitle("Tag Tracker Pro");
        deviceId = TagApp.deviceId(this);
        ScrollView sc = new ScrollView(this);
        root = new LinearLayout(this);
        root.setOrientation(LinearLayout.VERTICAL);
        int p = dp(20);
        root.setPadding(p, p, p, p);
        sc.addView(root);
        setContentView(sc);
        render();
    }

    private void render() {
        root.removeAllViews();
        boolean pro = false;
        String reason = "";
        try {
            JSONObject st = new JSONObject(TagApp.py(this).callAttr("license_state", deviceId).toString());
            pro = st.optBoolean("licensed");
            reason = st.optString("reason", "");
        } catch (Exception ignored) {
        }

        big(pro ? "✅ Pro is active" : "Free version");
        note(pro ? "All features are unlocked on this phone. Thank you!"
                : "FREE: 1 tag on 1 device, last 24 hours of history.\n\n"
                + "For 2+ tags and UNLIMITED-day tracking, contact the developer for a key.");

        head("A key unlocks");
        note("• Track multiple tags\n• Unlimited history (day → year) & trip replay\n"
                + "• CSV / GPX export\n• Theft / guard movement alerts\n• Google Drive auto-sync");

        head("Your Device ID");
        note("A Pro key is tied to THIS phone. Send this ID when you request a key:");
        final TextView idv = new TextView(this);
        idv.setText(deviceId);
        idv.setTextIsSelectable(true);
        idv.setPadding(dp(12), dp(10), dp(12), dp(10));
        idv.setTextSize(15);
        android.graphics.drawable.GradientDrawable g = new android.graphics.drawable.GradientDrawable();
        g.setCornerRadius(dp(10));
        g.setColor(0x1A64748B);
        idv.setBackground(g);
        root.addView(idv);
        button("Copy Device ID", v -> {
            ((ClipboardManager) getSystemService(Context.CLIPBOARD_SERVICE))
                    .setPrimaryClip(ClipData.newPlainText("Device ID", deviceId));
            toast("Device ID copied");
        });

        if (!pro) {
            head("Contact developer for a key");
            button("✉ Contact developer by Email", v -> requestByEmail());
            button("💬 Contact by SMS / WhatsApp / other", v -> requestByShare());
            note("Send your Device ID (above). You'll receive a key – paste it below to unlock this phone.");

            head("Enter your Pro key");
            final EditText key = new EditText(this);
            key.setHint("Paste license key");
            key.setInputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);
            root.addView(key);
            button("Unlock Pro", v -> unlock(key.getText().toString()));
            if (reason != null && !reason.isEmpty()) note("Note: " + reason);
        } else {
            button("Remove license from this phone", v -> {
                TagApp.py(this).callAttr("clear_license");
                toast("License removed");
                render();
            });
        }

        note("\nOpen-source (GPL-3.0). Contact: " + CONTACT_EMAIL);
    }

    private String emailBody() {
        return "Hello, I would like a Tag Tracker Pro key.\n\nMy Device ID: " + deviceId
                + "\n\n(App: Tag Tracker)";
    }

    private void requestByEmail() {
        Intent i = new Intent(Intent.ACTION_SENDTO, Uri.parse("mailto:" + CONTACT_EMAIL));
        i.putExtra(Intent.EXTRA_SUBJECT, "Tag Tracker Pro key request");
        i.putExtra(Intent.EXTRA_TEXT, emailBody());
        try {
            startActivity(Intent.createChooser(i, "Request Pro key by email"));
        } catch (Exception e) {
            toast("No email app found. Email " + CONTACT_EMAIL + " with your Device ID.");
        }
    }

    private void requestByShare() {
        Intent i = new Intent(Intent.ACTION_SEND);
        i.setType("text/plain");
        i.putExtra(Intent.EXTRA_TEXT, "Tag Tracker Pro key request. My Device ID: " + deviceId
                + " (send to " + CONTACT_EMAIL + ")");
        try {
            startActivity(Intent.createChooser(i, "Request Pro key via SMS / WhatsApp / other"));
        } catch (Exception e) {
            toast("Send your Device ID to " + CONTACT_EMAIL);
        }
    }

    private void unlock(String key) {
        if (key == null || key.trim().isEmpty()) {
            toast("Paste your key first");
            return;
        }
        new Thread(() -> {
            try {
                JSONObject r = new JSONObject(TagApp.py(this).callAttr("set_license", key.trim(), deviceId).toString());
                runOnUiThread(() -> {
                    if (r.optBoolean("licensed")) {
                        toast("Pro unlocked – thank you!");
                    } else {
                        toast("Key not valid: " + r.optString("reason", "unknown"));
                    }
                    render();
                });
            } catch (Exception e) {
                runOnUiThread(() -> toast("Error: " + e.getMessage()));
            }
        }).start();
    }

    // ---- tiny view helpers ----
    private int dp(int v) { return (int) (v * getResources().getDisplayMetrics().density); }

    private void big(String s) {
        TextView t = new TextView(this);
        t.setText(s);
        t.setTextSize(22);
        t.setTypeface(t.getTypeface(), android.graphics.Typeface.BOLD);
        t.setPadding(0, dp(4), 0, dp(4));
        root.addView(t);
    }

    private void head(String s) {
        TextView t = new TextView(this);
        t.setText(s);
        t.setTextSize(15);
        t.setTypeface(t.getTypeface(), android.graphics.Typeface.BOLD);
        t.setPadding(0, dp(18), 0, dp(4));
        root.addView(t);
    }

    private void note(String s) {
        TextView t = new TextView(this);
        t.setText(s);
        t.setTextSize(14);
        t.setPadding(0, dp(2), 0, dp(4));
        root.addView(t);
    }

    private void button(String s, android.view.View.OnClickListener onClick) {
        Button b = new Button(this);
        b.setText(s);
        b.setAllCaps(false);
        b.setOnClickListener(onClick);
        LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT);
        lp.topMargin = dp(6);
        root.addView(b, lp);
    }

    private void toast(String s) {
        runOnUiThread(() -> Toast.makeText(this, s, Toast.LENGTH_LONG).show());
    }
}
